nodeLinker: pnp

packageExtensions:
  "@types/react@*":
    peerDependenciesMeta:
      react:
        optional: true
  "@types/react-dom@*":
    peerDependenciesMeta:
      react:
        optional: true
